### ISSUE TITLE
Nashorn errors

### ISSUE THREAD

**Issue by whodidthis** [domkm/omelette#1]
Not sure if its just me requesting loads of renders on nashorn give occasional errors like `undefined bytecode (bug)`, and `Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs.` and `Error: Invariant Violation: ReactDOMForm: You can't call transferPropsTo() on a component that you don't own` especially when there are form elements on the page.

Getting this stuff on my project as well as this. Have you seen it? Keep F5 floored for some time

**Comment by domkm** [comment]
I am able to reproduce some of these. I think it is related to JS (and therefore Nashorn) being single-threaded. I was able to solve these issues by using a pool of render functions.

``` clojure
; omelette.render

; rename `render-fn` to `render-fn*` and
; create new `render-fn` uses a pool of `render-fn*` 

(defn render-fn []
  (let [queue (ref (clojure.lang.PersistentQueue/EMPTY))]
    (fn render [title state-edn]
      (let [rndr (dosync
                  (let [f (or (peek @queue) (render-fn*))]
                    (alter queue pop)
                    f))
            html (rndr title state-edn)]
        (dosync (alter queue conj rndr))
        html))))
```

**Comment by whodidthis** [comment]
I'm fairly sure ive seen a few of these even without much pressure applied but hopefully you are right. 

For reducing load an lru-cache with state as keys works great as well.
