### ISSUE TITLE
"lein demo" errors on initial run

### ISSUE THREAD

**Issue by blissdev** [domkm/omelette#4]
Here's the error I recieve:
https://gist.github.com/blissdev/c90a99de7e83baabb602

This is a little bit beyond my abilities to debug. Anything obvious?

`Leiningen 2.4.1 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM on Mac OS X 10.9.4`

**Comment by blissdev** [comment]
Same error in my VM with
`Leiningen 2.4.3 on Java 1.8.0_20 Java HotSpot(TM) 64-Bit Server VM on Ubuntu 14.04.1`

**Comment by domkm** [comment]
It works for me on `Leiningen 2.4.3 on Java 1.8.0_11 Java HotSpot(TM) 64-Bit Server VM on OS X 10.9.4`.

However, after updating to Java 1.8.0_20, I got the same error as you. There were [changes to Nashorn in 1.8.0_20](http://www.oracle.com/technetwork/java/javase/2col/8u20-bugfixes-2257730.html), but I don't know which change/s caused this error.

``` javascript
sablono.interpreter.wrap_form_element = function wrap_form_element(ctor, display_name) {
  return React.createClass({"render":function() {
    var this$ = this;
    return this$.transferPropsTo(ctor.call(null, {"children":this$.props["children"], "onChange":this$["onChange"], "value":this$.state["value"]}));
  }, ...
// It looks like `this$.state` is `null`.
```

Upgrading Om and React causes `javax.script.ScriptException: TypeError: null is not a function in <eval> at line number 19`. In other words, Nashorn doesn't even get to the Omelette code; it errors during the React preamble!

For now, I'd say downgrade to Java 1.8.0_11 until the issues with React are resolved.

**Comment by blissdev** [comment]
I don't know if this will help, but I did try out https://github.com/pleasetrythisathome/om-server-rendering which is a "stripped down" version of Omelette and it worked. Perhaps you can see a difference?
